### ISSUE TITLE
Reproducible Login command lines.

### ISSUE THREAD

**Issue by Vbitz** [tinyrange/tinyrange#3]
There's a `--load-definition` and `--save-definition` option in cmd/tinyrange/login.go already but it uses a private definition serializer that predated the general support.

I'd like to replace that with a more generic system. This will happen in a few stages so I can get underway with using it immediately.

- [x] Remove the old config system and replace it with a simpler YAML format.
- [ ] Support multiple plans in the YAML format.
- [x] Support external references in the YAML format.
- [x] Support nested builds in the YAML format.

**Comment by Vbitz** [comment]
Finished the first stage in 6b09dcf

**Comment by Vbitz** [comment]
For example this runs terastitcher inside TinyRange.

```yaml
version: 1
builder: wolfi
archives:
    - https://object-store.rc.nectar.org.au/v1/AUTH_dead991e1fa847e3afcca2d3a7041f5d/build/TeraStitcher-portable-1.11.10-Linux.tar.gz
packages:
    - zlib
    - libstdc++
environment:
    - PATH=/root/TeraStitcher-portable-1.11.10-Linux/
```

Run with `tinyrange login -c terastitcher.yml`
